### ISSUE TITLE
When Swapping Caps Lock With Escape, Caps Lock Key Triggers Both

### ISSUE THREAD

**Issue by fweth** [google/extra-keyboards-for-chrome-os#133]
Hello, not sure if this is the right place, but there is a problem with the Colemak and Workman keyboard layouts on ChromeOS Flex: If you swap Escape with Caps Lock in the settings, the key now triggers both, escape and caps lock behaviour.  So I always press CL followed by Shift to trigger escape and then unset caps lock.  However, this problem seems to only occur with Colemak and Workman, not with Qwerty, so I think it must be somehow connected to the layout maps.  Hope it can be easily fixed!

**Comment by colmbuckley** [comment]
Hey there -

This seems to be a bug in core Chrome OS functionality, rather than anything to do with this extension. This extension provides some additional layouts to those provided by core Chrome OS, but the main Workman and Colemak layouts are provided by the native system.

I would suggest you take a look at https://chromium.googlesource.com/chromiumos/docs/+/master/reporting_bugs.md which should give you an indication as to where and how you should report this behavior. Hopefully you get some response there.

Many thanks for the report,

Colm
