### ISSUE TITLE
Remap Brydge G-Type Fn key to Ctrl

### ISSUE THREAD

**Issue by ryan0x44** [google/extra-keyboards-for-chrome-os#57]
Here's the pixelbook bottom-left Ctrl key:

![Screenshot 2019-05-09 at 4 30 38 PM](https://user-images.githubusercontent.com/1902353/57492952-d31bcd00-7277-11e9-9c13-30fc1cea70db.png)

Here are the Brydge G-Type keyboard bottom-left Ctrl/Fn keys:

![Screenshot 2019-05-09 at 4 30 27 PM](https://user-images.githubusercontent.com/1902353/57492964-e0d15280-7277-11e9-8210-a0d7bc5728ad.png)

What would be great is if there was a way to remap 'Fn' to 'Ctrl' on the latter :)

**Comment by BetaLeaf** [comment]
While agreed, as Fn seemingly has no use on G-Type, but you should be aware that this repo is for virtual keyboards, not physical ones. These requests would be better directed towards the manufacturer's website. For your convenience, that link is https://www.brydge.com/pages/contact_us

**Comment by ryan0x44** [comment]
Thank you so much @BetaLeaf ! I'll close this and just follow-up with Brydge directly

**Comment by BetaLeaf** [comment]
Not a problem

**Comment by BetaLeaf** [comment]
I asked the brydge support team what the FN button does. This was their response. 

"Thank you for reaching out and that is a great question. As per Googles request, we have included the FN key, even though at this time there is no use for it. The reason for this is because with Chrome OS constantly updating, they have plans to begin using the key in the future with their software."
